const quotes : string[] = [
  "Genius is one percent inspiration and ninety-nine percent perspiration.",
  "Difficulties increase the nearer we get to the goal.",
  "Well begun is half done.",
  "What you give is what you get.",
  "Ideas are the beginning points of all fortunes.",
  "From error to error one discovers the entire truth.",
  "Well done is better than well said.",
  "Bite off more than you can chew, then chew it.",
  "One fails forward toward success.",
  "From small beginnings come great things.",
  "Learning is a treasure that will follow its owner everywhere",
  "A goal without a plan is just a wish.",
  "To succeed, we must first believe that we can.",
  "The best teacher is experience learned from failures.",
  "Don't wait. The time will never be just right.",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Striving for success without hard work is like trying to harvest where you haven’t planted",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Success isn’t overnight. It’s when every day you get a little better than the day before. It all adds up.",
  "Recipe for success: Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing.",
  "Failure is the opportunity to begin again more intelligently.",
  "If you fell down yesterday, stand up today.",
  "Don’t say you don’t have enough time. You have exactly the same amount of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo Di Vinci, Thomas Jefferson, and Albert Einstein.",
  "There are two kinds of people in this world: those who want to get things done and those who don’t want to make mistakes.",
  "There are no limits!",
  "I’m not telling you it is going to be easy — I’m telling you it’s going to be worth it.",
];

export default quotes;
